CREATE TABLE Checkin(
CheckID INT NOT NULL,
VolunteerID INT NOT NULL,
TimeIn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
Active BOOLEAN DEFAULT 1,
PRIMARY KEY(CheckID),
FOREIGN KEY(VolunteerID)REFERENCES Volunteer(VolunteerID) ON DELETE CASCADE
);