CREATE TABLE VolunteerLog(
LogID INT NOT NULL,
VolunteerID INT NOT NULL,
TaskID INT NOT NULL,
Date DATE NOT NULL,
TimeIn TIME NOT NULL,
TimeOut TIME NOT NULL,
TotalHours DECIMAL(5,2) NULL,
Comment MEDIUMTEXT,
PRIMARY KEY(LogID),
FOREIGN KEY(VolunteerID)REFERENCES Volunteer(VolunteerID) ON DELETE CASCADE,
FOREIGN KEY(TaskID)REFERENCES VolunteerTask(TaskID) ON DELETE CASCADE
);